(require 'helm-config)
(helm-descbinds-mode)
(require 'helm-migemo)
(setq helm-use-migemo t)
(helm-mode 1)
(define-key helm-find-files-map (kbd "C-h") 'helm-find-files-down-one-level)
(define-key helm-find-files-map (kbd "M-m") 'helm-execute-persistent-action)
(define-key evil-motion-state-map (kbd ";") #'evil-ex)
(define-key evil-normal-state-map (kbd "s") #'nil)
(define-key evil-normal-state-map (kbd "s s") #'helm-yasnippet-2)
(define-key evil-normal-state-map (kbd "s d") #'helm-find-files)
(define-key evil-normal-state-map (kbd "s g") #'helm-do-grep)
(define-key evil-normal-state-map (kbd "s f") #'helm-for-files)
(define-key evil-normal-state-map (kbd "s m") #'helm-recentf)
(define-key evil-normal-state-map (kbd "s b") #'helm-buffers-list)
(define-key evil-normal-state-map (kbd "s x") #'helm-M-x)
(define-key evil-normal-state-map (kbd "s y") #'helm-show-kill-ring)
